const translations = {
    zh: {
        title: {
            index: "MG Ads - 微软应用商店专属广告聚合平台 | 高收益流量变现",
            advertiser: "MG Ads - 广告主平台 | 精准触达Win10/Win11全球用户",
            publisher: "MG Ads - 开发者平台 | 微软应用商店广告变现",
            faq: "MG Ads - 常见问题解答 | 广告主&开发者必看"
        },
        description: {
            index: "MG Ads是专注于微软应用商店的广告聚合平台，为开发者提供高填充率广告位、智能结算系统和数据分析服务，助力提升收益20%+。支持一键接入UWP SDK，立即注册变现！",
            advertiser: "MG Ads提供微软应用商店（Win10/Win11）全球广告投放服务，覆盖100+国家高价值用户，广告填充率95%+，支持插屏、激励视频等多种形式，助您精准触达目标受众。立即申请投放！",
            publisher: "MG Ads是微软应用商店专属广告聚合平台，提供高填充率（95%+）广告变现方案，30分钟完成SDK接入，案例显示开发者收益提升20%。支持Unity、C++等主流引擎，立即注册！",
            faq: "MG Ads帮助中心：解答广告主投放、开发者SDK接入、广告填充率优化、收益结算等常见问题，提供详细教程与客服支持，快速解决您的疑问！"
        },
        nav: {
            traffic: "开发者",
            advertiser: "广告主",
            docs: "开发者文档",
            faq: "FAQ",
            about: "关于我们",
            login: "登录"
        },
        footer: {
            product: "产品",
            traffic: "开发者",
            advertiser: "广告主",
            docs: "文档",
            dev_docs: "开发者文档",
            compliance: "合规指南",
            privacy: "隐私政策",
            agreement: "开发者协议",
            about: "关于我们",
            intro: "公司介绍",
            coop: "商务合作",
            contact: "联系我们",
            support: "支持",
            faq: "常见问题",
            copyright: "北京奇游灵动科技有限公司版权所有 COPYRIGHT© 2016-2025 MIRACLE GAMES INC ALL RIGHTS RESERVED.<br>经营许可证编号: 京B2-20230011 | 京ICP备16022485号-1 | 京网文[2017]1979-172号 | 京公网安备11010502041007号"
        },
        index: {
            s1_title_line1: "你专注创作",
            s1_title_line2: "我们助你变现",
            s1_subtitle: "MG Ads是Win10/Win11全球广告聚合平台",
            s1_desc: "作为微软全球顶级合作伙伴之一 MG Ads能帮助你一站式解决微软应用商店内流量变现难题 助你高效且便捷地实现全球化增长",
            s1_btn: "立即开始",
            s2_title: "把握高价值流量，收入突飞猛进",
            s2_card1_title: "总用户量",
            s2_card1_value: "8363",
            s2_card1_unit: "万",
            s2_card2_title: "全球开发者",
            s2_card3_title: "广告展示量",
            s2_card4_title: "填充率",
            s2_card4_value: "高",
            s2_calc_input: "请输入DAU值",
            s2_calc_output: "预估收益",
            s2_calc_btn: "计算收益",
            s2_calc_desc: "您可以通过输入DAU值，了解到我们给到的预估广告收入",
            s3_title_line1: "流量庞大",
            s3_title_line2: "高价值用户触手可得",
            s3_desc: "覆盖微软应用商店全球高价值流量 与Microsoft深度合作伙伴 将祝您精准触达目标用户、实现高效获取高价值目标用户",
            s3_btn: "了解更多",
            s4_title_line1: "高效收益",
            s4_title_line2: "让游戏应用变现提升数倍",
            s4_desc: "全球优质广告资源加持 与多家顶级广告供应商密切合作 确保用户使用体验的同时 助你轻松提升收益",
            s4_btn: "了解更多",
            s5_title: "多元化广告形式，给您不一样的体验",
            s5_carousel_1: "横幅广告",
            s5_carousel_2: "全屏广告",
            s5_carousel_3: "对联广告",
            s5_carousel_4: "插屏广告",
            s5_carousel_5: "退屏广告",
            s5_carousel_6: "开屏广告",
            s6_title: "深受微软应用商店全球开发者信赖",
            s6_case1_text: "“Cooking City”由Miracle Games于2021年9月10日发布在微软应用商店，并多次获得微软官方的全球 推荐，深受微软商店用户喜爱。在接入MG Ads SDK 后，日活跃用户增长了20%，人均收入提升了15%。",
            s6_case2_text: "\"Snack Short\"由Miracle Games于2024年10月23日发布在微软应用商店。在MG Ads提供的数据分析服务支持下，成功识别出最受欢迎的功能模块，并据此进行了有针对性的优化，最终实现了下载量的翻倍增长。同时，通过MG Ads接入Google AdSense等广告，实现了便捷高效的流量变现",
            s7_title: "加入我们，助力你的成长",
            s7_btn1: "高价值流量入口",
            s7_btn2: "高效变现入口",
            s7_text: "订阅即可获得更多相关行业信息及动态走向",
            s7_email_placeholder: "请输入您的邮箱"
        },
        advertiser: {
            s1_title_line1: "流量庞大",
            s1_title_line2: "高价值用户触手可得",
            s1_desc: "覆盖微软应用商店全球高价值流量<br>与Microsoft深度合作伙伴<br>将祝您精准触达目标用户、实现高效获取高价值目标用户",
            s1_btn: "了解更多",
            s2_title_line1: "在微软游戏生态中",
            s2_title_line2: "实现稳健且高效的增长",
            s2_desc: "我们已掌握微软应用商店头部开发者及众多中小型开发者的优质流量<br>并提供完善的技术支持文档，确保适配多种开发引擎<br>从而实现稳定、高效的高质量用户获取",
            s2_small_box_value: "15",
            s2_small_box_unit: "亿",
            s2_card1_value: "2",
            s2_card1_unit: "亿",
            s2_box_title: "微软应用商店月活跃设备",
            s2_card1_title: "高质量游戏玩家",
            s2_card2_title: "美国单一市场贡献收入",
            s2_card3_title: "用户付费意愿",
            s2_card4_title: "覆盖全球地区",
            s3_title_line1: "核心广告价值：玩家用户的",
            s3_title_line2: "深度参与与卓越的变现能力",
            s3_desc: "对于广告平台而言，用户的注意力与付费意愿是关键指标<br>微软应用商店在游戏领域的卓越表现，直接转化为极具价值的广告机会",
            s3_frame1_title: "庞大<br>的玩家<br>基数",
            s3_frame1_desc: "2.01亿（2.01B)月活跃设备；<br>\"这是一个规模巨大、目标明确的优质受众群\"",
            s3_frame2_title: "极高<br>的用户<br>粘性",
            s3_frame2_desc: "2.38亿（2.38B）小时玩家总在线时长；<br>\"巨大的用户投入时间为广告展示提供了丰富的场景和大量的曝光机会\"",
            s3_frame3_title: "适配<br>的年龄<br>用户",
            s3_frame3_desc: "18-34岁用户高达58%；<br>\"这个群体是数字消费的主力军，对新事物接受度高，是广告活动的理想目标人群\"",
            s4_title: "进入微软生态，开启高价值流量",
            s4_btn: "即刻开始"
        },
        publisher: {
            s1_title_line1: "高效收益",
            s1_title_line2: "让游戏应用变现提升数倍",
            s1_desc: "全球优质广告资源加持<br>与多家顶级广告供应商密切合作<br>确保用户使用体验的同时<br>助你轻松提升收益",
            s1_btn: "了解更多",
            s2_title_sub: "我们是谁：",
            s2_title_main_prefix: "深耕微软生态的",
            s2_title_main_suffix: "变现专家",
            s2_desc: "MG Ads是专为微软应用商店及Windows生态量身打造的一站式广告聚合与增长平台",
            s2_box1: "我们的团队在Windows开发与广告技术领域拥有超过10年的深厚积累。 我们深刻理解UWP/WinUI架构的特性、微软应用商店的审核政策以及Windows全球用户的行为模式。",
            s2_box2: "我们的使命是\"让开发者的商业化变得简单而高效\"，这与微软赋能开发者的理念完全同频。 一个能让开发者获得丰厚汇报的生态，才是一个健康、有活力的生态。",
            s3_title_sub: "精准洞察：",
            s3_title_main_prefix: "微软开发者的",
            s3_title_main_suffix: "核心痛点",
            s3_desc: "MG Ads的诞生，正式为了系统性地解决这些问题",
            s3_card1_title: "变现渠道匮乏与低效",
            s3_card1_desc: "许多主流广告平台对UWP/Win32 应用的支持薄弱或缺失，导致开发 者面临广告填充率低、eCPM不具 竞争力的困境。",
            s3_card2_title: "技术集成复杂",
            s3_card2_desc: "针对不同开发引擎（Unity， Cocos，UE5，C++等）缺乏统一、 标准发的SDK接入方案，移植和对 接成本高。",
            s3_card3_title: "对用户体验的顾虑",
            s3_card3_desc: "担心广告影响应用性能、启动速度 及界面美观度，破坏Windows原 生应用的流畅体验。",
            s4_title_sub: "战略与技术对齐：",
            s4_title_main_prefix: "为何MG Ads是",
            s4_title_main_suffix: "绝佳选择",
            s4_frame1_title: "1.无与伦比的生态契合度：",
            s4_frame1_desc: "专为Windows优化，支持开屏、横幅、插屏、视频、对联、退屏等多种广告形式，并能完美适配平板模式、 桌面模式切换等复杂场景。",
            s4_frame2_title: "2.强大的技术继承与微软技术栈融合：",
            s4_frame2_desc: "我们提供业界全面的SDK支持，覆盖Unity、Cocos2d-x、Unreal Engine、HTML5、以及原生的C++、 C#等主流开发引擎；同时我们提供Visual Studio Nuget包和丰富的示例代码，开发者平均可在1.5个工 作日内完成集成。",
            s4_btn: "下载SDK",
            s5_title_sub: "核心价值主张：",
            s5_title_main: "超越期待的<span class=\"text-blue\">三大优势</span>",
            s5_left1_title: "1.收益潜力超预期——聚合顶级资源，收益最大化",
            s5_left1_desc: "智能竞价引擎：我们采用实时竞价（RTB）技术，而非低效的\"瀑布流\"，确保每一次广告展示都能获得最高出价，帮助开发者的广告收益平均提升20%-40%。",
            s5_left2_title: "2.开发体验超预期——极简接入，透明可控",
            s5_left2_desc: "\"一行代码\"接入：我们将复杂的广告逻辑封装在SDK内部，开发者只需调用几行API即可展示广告，接入过程极其简单。",
            s5_right1_title: "3.安全稳定超预期——企业级服务保障",
            s5_right1_desc: "精准归因与防作弊：在UWP环境下，我们接入了AppsFlyer、Kochava等第三方工具，确保数据公正透明，有效防御无效流量。<br>高可用架构：我们的SSP系统与广告投放引擎拥有99.9%的服务可用性，让开发者无后顾之忧。",
            s6_title: "全球多家广告网络助力推动营收增长"
        },
        faq: {
            title: "常见问题",
            btn_more: "更多内容",
            q1: "如果使用MG广告赚取收益，合作模式又是什么？",
            a1: "MG广告采用CPI计费模式，指的是用户通过广告下载并打开应用后，计算为一个CPI；除MG广告外，我们还接入了多家全球广告网络提供多元化广告素材，这些三方广告网络的计费模式大多数以CPS、CPM等方式进行结算。",
            q2: "开发者们什么时候可以收到广告收益？",
            a2: "结算周期为1个月（即按公历自然月计算，每月1日零时至当月最后一天24时整为一个结算周期）。MG公司在每个月第【15】个自然日之前通过电子邮件的方式向开放者提供上一个结算周期的结算数据。开发者在确认结算数据后，应【5】个自然日内向MG公司的运营人员开具对应金额的、等额合法的、符合MG公司要求的发票。MG公司收到发票的第【7】个自然日内将对应的分成款项支付给开发者指定的银行账号。",
            q3: "开发者如何查看收入报告？",
            a3: "开发者可以通过Miracle Games后台，广告平台\"报告\"中查看。",
            q4: "广告数据是实时的吗？",
            a4: "是的，MG广告的数据会每10分钟进行更新。",
            q5: "是否需要签订长期合同？",
            a5: "是的，开发者需要与MG公司签订一份合作协议，开发者可以通过电子邮件Developer@mguwp.com联系我们洽淡协议。",
            q6: "MG Ads SDK是否只支持UWP版本？",
            a6: "目前MG广告只支持UWP业务，后续我们将开通移动手机广告业务，敬请期待。",
            q7: "开发者该如何使用Miracle Games后台，怎么创建广告？",
            a7: "我们对MG后台怎样创建广告进行了详细的图文说明，详情请点击<a href=\"https://doc.mguwp.net/DevelopersQ&A.html\" target=\"_blank\" style=\"color: #0078D7; text-decoration: underline;\">MG后台操作指南</a>。",
            q8: "广告无法正常展示怎么办？",
            a8: "首先，广告首次展示会有几秒钟的延迟，您需要耐心等待广告缓存完毕，其次，您需要检查MG后台的广告位配置是否有错误，广告位ID是否调用错误，广告开关是否是开启状态。最后，所有检查完毕后依然没有广告展示，您可以联系MG的运营人员协助处理。",
            contact_title: "我们该如何联系Miracle Games进行合作洽谈？"
        }
    },
    en: {
        title: {
            index: "MG Ads - Microsoft Store Exclusive Ad Aggregation Platform | Maximize Your Traffic Revenue",
            advertiser: "MG Ads - Advertiser | Precisely Engage Windows 10/11 Users Worldwide",
            publisher: "MG Ads - Developer | Microsoft Store Ad Monetization",
            faq: "MG Ads - FAQ | Essential Information for Advertisers & Developers"
        },
        description: {
            index: "MG Ads is a Microsoft Store - focused ad aggregation platform that provides developers with high-fill-rate placements, smart settlement tools, and powerful analytic - helping you increase revenue by 20% or more. Integrate instantly with our UWP SDK and start monetizing now!",
            advertiser: "MG Ads provides global advertising services for the Microsoft Store (Windows 10/11), reaching high-value users across 100+ countries. With fill rates above 95% and support for formats such as interstitial and rewarded videos, we help you precisely reach your target audience. Start your campaign today!",
            publisher: "MG Ads is a Microsoft Store - exclusive ad aggregation platform providing high-fill-rate (95%) monetization solutions. With a 30-minute SDK integration process and proven cases showing a 20% revenue uplift, we support major engines including Unity and C++. Register now!",
            faq: "MG Ads Help Center: Find answers to common questions about advertiser campaigns, developer SDK integration, fill-rate optimization, revenue settlement, and more. Access detailed guides and customer support to quickly resolve your issues!"
        },
        nav: {
            traffic: "Developer",
            advertiser: "Advertiser",
            docs: "Developer Docs",
            faq: "FAQ",
            about: "About Us",
            login: "Login"
        },
        footer: {
            product: "Product",
            traffic: "Developer",
            advertiser: "Advertiser",
            docs: "Docs",
            dev_docs: "Developer Docs",
            compliance: "Compliance Guide",
            privacy: "Privacy Policy",
            agreement: "Developer Agreement",
            about: "About Us",
            intro: "Company Intro",
            coop: "Business Coop",
            contact: "Contact Us",
            support: "Support",
            faq: "FAQ",
            copyright: "COPYRIGHT© 2016-2025 MIRACLE GAMES INC ALL RIGHTS RESERVED.<br>License No.: Beijing B2-20230011 | Beijing ICP 16022485-1 | Beijing Network Culture [2017]1979-172 | Beijing Public Security 11010502041007"
        },
        index: {
            s1_title_line1: "You create",
            s1_title_line2: "We help you monetize",
            s1_subtitle: "MG Ads is a global ad aggregation platform built for the Windows 10/11 ecosystem",
            s1_desc: "As one of Microsoft’s top global partners, MG Ads helps you solve all traffic monetization challenges in the Microsoft Store with a one-stop solution, enabling efficient and seamless global growth",
            s1_btn: "Start Now",
            s2_title: "Unlock high-value traffic and drive explosive revenue growth",
            s2_card1_title: "Total Users",
            s2_card1_value: "83.63",
            s2_card1_unit: "M",
            s2_card2_title: "Global Developers",
            s2_card3_title: "Ad Impressions",
            s2_card4_title: "Fill Rate",
            s2_card4_value: "High",
            s2_calc_input: "Enter DAU",
            s2_calc_output: "Estimated Revenue",
            s2_calc_btn: "Calculate Revenue",
            s2_calc_desc: "Enter DAU to see your estimated ad revenue",
            s3_title_line1: "Large Scale Traffic",
            s3_title_line2: "High Value Users",
            s3_desc: "Tap into global high-value traffic in the Microsoft Store As a strategic Microsoft partner, MG Ads helps you reach your target users with precision and maximize acquisition of high-value audiences",
            s3_btn: "More Details",
            s4_title_line1: "Efficient Monetization",
            s4_title_line2: "and Revenue Increase",
            s4_desc: "Powered by premium global ad resources and close collaborations with top-tier ad vendors, we help you boost revenue effortlessly while maintaining an excellent user experience",
            s4_btn: "More Details",
            s5_title: "Diverse Ad Formats for a Unique Experience",
            s5_carousel_1: "Banner Ad",
            s5_carousel_2: "Pop Up Ad",
            s5_carousel_3: "Vertical Ad",
            s5_carousel_4: "Square Ad",
            s5_carousel_5: "Full Screen Ad",
            s5_carousel_6: "Open Screen Ad",
            s6_title: "Trusted by developers worldwide on the Microsoft Store",
            s6_case1_text: "\"Cooking City\" released by Miracle Games on Microsoft Store on Sep 10, 2021, has been featured globally by Microsoft multiple times After integrating MG Ads SDK, DAU increased by 20% and ARPU increased by 15%",
            s6_case2_text: "\"Snack Short\" released by Miracle Games on Oct 23, 2024 With data analysis support from MG Ads, optimized popular features led to doubled downloads Integrating Google AdSense via MG Ads achieved efficient traffic monetization",
            s7_title: "Join us and accelerate your growth",
            s7_btn1: "High-value traffic gateway",
            s7_btn2: "Efficient monetization gateway",
            s7_text: "Subscribe for more industry insights and trends",
            s7_email_placeholder: "Enter your email"
        },
        advertiser: {
            s1_title_line1: "Large Scale Traffic",
            s1_title_line2: "High Value Users",
            s1_desc: "Tap into global high-value traffic in the Microsoft Store As a strategic Microsoft partner, MG Ads helps you reach your target users with precision and maximize acquisition of high-value audiences",
            s1_btn: "More Details",
            s2_title_line1: "Achieve steady and efficient growth",
            s2_title_line2: "within the Microsoft gaming ecosystem",
            s2_desc: "We have access to premium traffic from top Microsoft Store developers as well as numerous small- and medium-sized developers With comprehensive technical documentation and support, we ensure compatibility across multiple development engines, enabling stable, efficient acquisition of high-quality users",
            s2_small_box_value: "1500",
            s2_small_box_unit: "M",
            s2_card1_value: "200",
            s2_card1_unit: "M",
            s2_box_title: "MAD on the Microsoft Store",
            s2_card1_title: "High Quality Players",
            s2_card2_title: "Revenue from the U.S.",
            s2_card3_title: "ARPPU",
            s2_card4_title: "Covering Global Regions",
            s3_title_line1: "Core Advertising Value: Deep Player Engagement",
            s3_title_line2: "and Outstanding Monetization",
            s3_desc: "For advertising platforms, user attention and willingness to spend are key metrics The Microsoft Store's outstanding performance in the gaming sector directly translates into highly valuable advertising opportunities",
            s3_frame1_title: "User Base",
            s3_frame1_desc: "2.01B MAD; \"A large-scale, high-quality audience with clear targeting potential\"",
            s3_frame2_title: "User Engage",
            s3_frame2_desc: "2.38B total player hours; \"Significant user time investment provides rich scenarios and abundant opportunities for ad impressions\"",
            s3_frame3_title: "Age",
            s3_frame3_desc: "58% of users aged 18–34; \"This group is the main force of digital consumption, highly receptive to new experiences, and an ideal target for advertising campaigns\"",
            s4_title: "Enter the Microsoft ecosystem and unlock high-value traffic",
            s4_btn: "Start Now"
        },
        publisher: {
            s1_title_line1: "Efficient Monetization",
            s1_title_line2: "and Revenue Increase",
            s1_desc: "Powered by premium global ad resources and close collaborations with top-tier ad vendors, we help you boost revenue effortlessly while maintaining an excellent user experience",
            s1_btn: "More Details",
            s2_title_sub: "Who We Are:",
            s2_title_main_prefix: "Monetization experts deeply rooted in the ",
            s2_title_main_suffix: "Microsoft ecosystem",
            s2_desc: "MG Ads is a one-stop ad aggregation and growth platform tailored specifically for the Microsoft Store and the Windows ecosystem",
            s2_box1: "Deep Expertise: Our team brings over 10 years of experience in Windows development and ad technology We deeply understand the characteristics of the UWP/WinUI architecture, the Microsoft Store's certification policies, and the behavior patterns of Windows users worldwide",
            s2_box2: "Aligned Mission: Our mission is to \"make developer monetization simple and efficient,\" fully aligned with Microsoft's vision of empowering developers A thriving ecosystem is one where developers can achieve meaningful and sustainable returns",
            s3_title_sub: "Precise Insights:",
            s3_title_main_prefix: "Addressing the Core Pain Points of ",
            s3_title_main_suffix: "Microsoft Developers",
            s3_desc: "MG Ads was created to systematically address these challenges",
            s3_card1_title: "Limited Monetization Channels",
            s3_card1_desc: "Many mainstream ad platforms offer weak or no support for UWP/Win32 applications, leaving developers with low ad fill rates and non-competitive eCPMs",
            s3_card2_title: "Complex Technical Integration",
            s3_card2_desc: "There is a lack of unified, standardized SDK solutions for different development engines (Unity, Cocos, UE5, C++, etc.), resulting in high porting and integration costs",
            s3_card3_title: "Concerns About User Experience",
            s3_card3_desc: "Developers worry that ads may impact app performance, startup speed, and visual design, potentially compromising the smooth experience expected from native Windows applications",
            s4_title_sub: "Strategic and Technical Alignment:",
            s4_title_main_prefix: "Why MG Ads Is the",
            s4_title_main_suffix: "Perfect Choice",
            s4_frame1_title: "1.Unmatched Ecosystem Fit:",
            s4_frame1_desc: "Optimized specifically for Windows, MG Ads supports a wide range of ad formats, including splash, banner, interstitial, video, native, and exit ads It also seamlessly adapts to complex scenarios such as tablet-to-desktop mode switching",
            s4_frame2_title: "2.Powerful Technical Inheritance and Microsoft Tech Stack Integration:",
            s4_frame2_desc: "We provide the industry's most comprehensive SDK support, covering Unity, Cocos2d-x, Unreal Engine, HTML5, as well as native C++ and C# Additionally, we offer Visual Studio NuGet packages and extensive sample code, enabling developers to integrate and inherit our SDK in an average of just 1.5 working days",
            s4_btn: "Download SDK",
            s5_title_sub: "Core Value Proposition:",
            s5_title_main: "Three Advantages That <span class=\"text-blue\">Exceed Expectations</span>",
            s5_left1_title: "1.Exceptional Revenue Potential – Aggregating Top Resources, Maximizing Income",
            s5_left1_desc: "Intelligent Bidding Engine: We use real-time bidding (RTB) technology instead of inefficient \"waterfall\" methods, ensuring every ad impression achieves the highest bid, boosting developers' ad revenue by an average of 20%-40%",
            s5_left2_title: "2.Seamless Developer Experience – Minimal Integration, Full Transparency",
            s5_left2_desc: "\"One-Line Code\" Integration: Our highly encapsulated API allows developers to display ads with just a few lines of code, making integration extremely simple and controllable",
            s5_right1_title: "3.Enterprise-Grade Reliability and Security",
            s5_right1_desc: "Accurate Attribution & Fraud Prevention: Within the UWP environment, we integrate third-party tools like AppsFlyer and Kochava to ensure fair and transparent data, effectively defending against invalid traffic<br>High Availability Architecture: Our SSP system and ad delivery engine maintain 99.9% service uptime, giving developers peace of mind",
            s6_title: "Global ad networks help drive revenue growth"
        },
        faq: {
            title: "Common Questions",
            btn_more: "More Details",
            q1: "What is the cooperation model if I use MG Ads to monetize?",
            a1: "MG Ads uses a CPI billing model, meaning a download and open of the app via an ad counts as one CPI Besides MG Ads, we integrate with multiple global ad networks providing diverse ad creatives, most of which settle via CPS, CPM, etc",
            q2: "When will developers receive ad revenue?",
            a2: "The settlement cycle is 1 month (calendar month) MG provides settlement data via email before the 15th of each month for the previous cycle After confirmation, developers must issue a valid invoice within 5 days MG will pay to the designated bank account within 7 days of receiving the invoice",
            q3: "How can developers view revenue reports?",
            a3: "Developers can view them in the \"Reports\" section of the Miracle Games backend ad platform",
            q4: "Is ad data real-time?",
            a4: "Yes, MG Ads data is updated every 10 minutes",
            q5: "Is a long-term contract required?",
            a5: "Yes, developers need to sign a cooperation agreement with MG You can contact us via Developer@mguwp.com to discuss the agreement",
            q6: "Does MG Ads SDK only support UWP version?",
            a6: "Currently, MG Ads only supports UWP business We will launch mobile ad business in the future, so stay tuned",
            q7: "How do developers use the Miracle Games backend to create ads?",
            a7: "We have detailed graphic instructions on how to create ads in the MG backend Please click <a href=\"https://doc.mguwp.net/DevelopersQ&A.html\" target=\"_blank\" style=\"color: #0078D7; text-decoration: underline;\">MG Backend Operation Guide</a> for details",
            q8: "What if ads are not displaying properly?",
            a8: "First, there is a few seconds delay for the first ad display, please wait for caching Second, check if the ad slot configuration in MG backend is correct, if the ad slot ID is wrong, or if the ad switch is on Finally, if still no ads after checking, contact MG operations for assistance",
            contact_title: "Business Contact Information"
        }
    }
};

